# Informations application
app.name=infra-demo
app.version=1.0.0

# Port embarqué (utilisé uniquement en mode standalone, pas sur Liberty)
server.port=8080

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
