# Informations application
app.name=infra-demo-02
app.version=1.0.0

# Port embarqué (utilisé uniquement en mode standalone, pas sur Liberty)
server.port=8091

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

